/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Algorithm_JNIWrapper */

#ifndef _Included_Algorithm_JNIWrapper
#define _Included_Algorithm_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Algorithm_JNIWrapper
 * Method:    landmarkDetection
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Algorithm_JNIWrapper_landmarkDetection
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
